spring:
  application:
    name: finza_backend

  datasource:
    url: jdbc:postgresql://localhost:5432/finza
    username: postgres
    password: "@Vtd2003"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: finza_super_secret_key_2024_make_it_long
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000